language: cpp
sudo: required
dist: trusty
compiler:
  - clang++
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - cmake
      - gcc-5
      - g++-5
      - clang-3.9
script:
  - cd && cmake $TRAVIS_BUILD_DIR && cmake --build .
